# Generated by Django 5.0.1 on 2024-01-21 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_id', models.IntegerField()),
                ('location_address', models.CharField(max_length=300)),
                ('longtitude', models.FloatField(blank=True, default=None, null=True)),
                ('latitude', models.FloatField(blank=True, default=None, null=True)),
                ('centreline_type', models.CharField(blank=True, default=None, max_length=300, null=True)),
                ('centreline_id', models.CharField(blank=True, default=None, max_length=300, null=True)),
                ('px', models.CharField(blank=True, default=None, max_length=300, null=True)),
                ('latest_count_date', models.DateTimeField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
