# Generated by Django 5.0.1 on 2024-01-21 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torontoevents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facilities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facility_id', models.IntegerField()),
                ('location_id', models.IntegerField()),
                ('facility_display_name', models.CharField(blank=True, default=None, max_length=300, null=True)),
                ('permit', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('facility_type', models.CharField(blank=True, default=None, max_length=300, null=True)),
                ('facility_rating', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('asset_name', models.CharField(blank=True, default=None, max_length=300, null=True)),
            ],
        ),
    ]
