# Generated by Django 5.0.1 on 2024-01-28 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torontoevents', '0003_facility_delete_facilities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facility',
            name='location_id',
            field=models.IntegerField(),
        ),
    ]
