# Generated by Django 5.0.1 on 2024-02-02 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torontoevents', '0005_registeredprogram'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registeredprogram',
            name='max_age',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='registeredprogram',
            name='min_age',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
    ]
