# Generated by Django 5.0.1 on 2024-02-06 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torontoevents', '0006_alter_registeredprogram_max_age_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DropInProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_id', models.IntegerField()),
                ('course_id', models.IntegerField()),
                ('course_title', models.CharField(blank=True, default=None, max_length=300, null=True)),
                ('min_age', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('max_age', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('date_from', models.DateField()),
                ('date_range', models.CharField(blank=True, default=None, max_length=3000, null=True)),
                ('start_date_time', models.DateField()),
                ('start_hour', models.IntegerField()),
                ('start_min', models.IntegerField()),
                ('end_hour', models.IntegerField()),
                ('end_min', models.IntegerField()),
                ('category', models.CharField(blank=True, default=None, max_length=300, null=True)),
                ('first_date', models.DateField()),
                ('last_date', models.DateField()),
            ],
        ),
    ]
