# Generated by Django 5.0.1 on 2024-02-06 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torontoevents', '0007_dropinprogram'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dropinprogram',
            name='date_from',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
