# Generated by Django 5.0.1 on 2024-02-06 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torontoevents', '0008_alter_dropinprogram_date_from'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dropinprogram',
            name='date_from',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
