# Generated by Django 5.0.1 on 2024-02-06 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torontoevents', '0009_alter_dropinprogram_date_from'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dropinprogram',
            name='date_from',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
    ]
