# Generated by Django 5.0.1 on 2024-02-06 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torontoevents', '0010_alter_dropinprogram_date_from'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dropinprogram',
            name='first_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='dropinprogram',
            name='last_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='dropinprogram',
            name='start_date_time',
            field=models.DateTimeField(),
        ),
    ]
